export const pouch_discount = {
  rate_1: 0.93,
  rate_2: 0.86,
  quantity_1: 2,
  quantity_2: 4,
};
export const bag_discount = {
  rate_1: 0.94,
  rate_2: 0.88,
  quantity_1: 3,
  quantity_2: 6,
};
export const free_shipping_threshold = 49;

export const countries = [
  { value: "United States", label: "United States" },
  { value: "Canada", label: "Canada" },
  // Thêm các quốc gia khác nếu cần
];

export const statesAndProvinces = [
  // 🇺🇸 United States
  { value: "Alabama", label: "Alabama" },
  { value: "Alaska", label: "Alaska" },
  { value: "Arizona", label: "Arizona" },
  { value: "Arkansas", label: "Arkansas" },
  { value: "California", label: "California" },
  { value: "Colorado", label: "Colorado" },
  { value: "Connecticut", label: "Connecticut" },
  { value: "Delaware", label: "Delaware" },
  { value: "Florida", label: "Florida" },
  { value: "Georgia", label: "Georgia" },
  { value: "Hawaii", label: "Hawaii" },
  { value: "Idaho", label: "Idaho" },
  { value: "Illinois", label: "Illinois" },
  { value: "Indiana", label: "Indiana" },
  { value: "Iowa", label: "Iowa" },
  { value: "Kansas", label: "Kansas" },
  { value: "Kentucky", label: "Kentucky" },
  { value: "Louisiana", label: "Louisiana" },
  { value: "Maine", label: "Maine" },
  { value: "Maryland", label: "Maryland" },
  { value: "Massachusetts", label: "Massachusetts" },
  { value: "Michigan", label: "Michigan" },
  { value: "Minnesota", label: "Minnesota" },
  { value: "Mississippi", label: "Mississippi" },
  { value: "Missouri", label: "Missouri" },
  { value: "Montana", label: "Montana" },
  { value: "Nebraska", label: "Nebraska" },
  { value: "Nevada", label: "Nevada" },
  { value: "New Hampshire", label: "New Hampshire" },
  { value: "New Jersey", label: "New Jersey" },
  { value: "New Mexico", label: "New Mexico" },
  { value: "New York", label: "New York" },
  { value: "North Carolina", label: "North Carolina" },
  { value: "North Dakota", label: "North Dakota" },
  { value: "Ohio", label: "Ohio" },
  { value: "Oklahoma", label: "Oklahoma" },
  { value: "Oregon", label: "Oregon" },
  { value: "Pennsylvania", label: "Pennsylvania" },
  { value: "Rhode Island", label: "Rhode Island" },
  { value: "South Carolina", label: "South Carolina" },
  { value: "South Dakota", label: "South Dakota" },
  { value: "Tennessee", label: "Tennessee" },
  { value: "Texas", label: "Texas" },
  { value: "Utah", label: "Utah" },
  { value: "Vermont", label: "Vermont" },
  { value: "Virginia", label: "Virginia" },
  { value: "Washington", label: "Washington" },
  { value: "West Virginia", label: "West Virginia" },
  { value: "Wisconsin", label: "Wisconsin" },
  { value: "Wyoming", label: "Wyoming" },

  // 🇨🇦 Canada
  { value: "Alberta", label: "Alberta" },
  { value: "British Columbia", label: "British Columbia" },
  { value: "Manitoba", label: "Manitoba" },
  { value: "New Brunswick", label: "New Brunswick" },
  { value: "Newfoundland and Labrador", label: "Newfoundland and Labrador" },
  { value: "Northwest Territories", label: "Northwest Territories" },
  { value: "Nova Scotia", label: "Nova Scotia" },
  { value: "Nunavut", label: "Nunavut" },
  { value: "Ontario", label: "Ontario" },
  { value: "Prince Edward Island", label: "Prince Edward Island" },
  { value: "Quebec", label: "Quebec" },
  { value: "Saskatchewan", label: "Saskatchewan" },
  { value: "Yukon", label: "Yukon" },
];

export const homePageHeroBanners = [
  "/images/home/hero-banner-1.webp",
  "/images/home/hero-banner-2.webp",
  "/images/home/hero-banner-3.webp",
  "/images/home/hero-banner-4.webp",
];

export const homePageReviews = [
  {
    rating: 5,
    title: "Exactly what I expect in a Vietnamese coffee. Made me miss home",
    desc: "I’m first-generation Vietnamese-American and your coffee takes me back to my bà ngoại’s kitchen where I would eagerly follow her around to see if she’ll make me a glass of her delicious iced coffee. I made one for myself today to honor my grandma. I miss her. 🥹",
    reviewer: " Megan T. ",
    img: "/images/home/review-product-1.png",
    product: " HaNoi Coffee (100% Robusta) ",
  },
  {
    rating: 5,
    title: "Very decadent, rich, and pretty strong",
    desc: "The hype surrounding Vietnamese coffee got me curious so I have been trying different brands for a while now. I liked a few, but most are meehhhh, nothing special really. But I liked this Saigon OG. The caffeine jolt was just right and I didn't feel jittery at all. Aroma and flavor were just excellent too! Really strong, decadent, and very flavorful!",
    reviewer: " Mariam A. ",
    img: "/images/home/review-product-2.png",
    product: " SaiGon OG Coffee (Robusta x Arabica X Peaberry) ",
  },
  {
    rating: 5,
    title: "Genuine Vietnamese coffee, loved the coconut mill",
    desc: "8/10 for flavor and effect. I liked the overall flavor of this instant coffee. It has that genuine Vietnamese vibes, bold and very flavorful. But I find the coconut milk a bit too pronounced for my taste. I’m going to try the milk version next",
    reviewer: " Mariam F. ",
    img: "/images/home/review-product-3.png",
    product: " Vietnamese Coffee 2.0 (Instant Coconut Latte) ",
  },
  {
    rating: 5,
    title: "Amazing coffee and perfect as gifts",
    desc: "This is sooo amazing! Sweet and creamy and perfectly complements the strong coffee flavor of Vietnamese coffee. I already ordered a new bag for myself, and three more to give as gifts to my close friends.",
    reviewer: " Lina M. ",
    img: "/images/home/review-product-4.png",
    product: " Vietnamese Coffee 2.0 (Instant Milk Latte) ",
  },
  {
    rating: 5,
    title: "Real deal vietnamese coffee",
    desc: "100% genuine Vietnamese coffee. It has the familiar bold flavors and strong energy kick i remember from my time in vietnam. Cafely nailed it.",
    reviewer: " Amina H. ",
    img: "/images/home/review-product-5.png",
    product: " Vietnamese Coffee 2.0 (Instant Espresso) ",
  },
  {
    rating: 5,
    title: "So gooood!",
    desc: "This is seriously so delicious! For an instant coffee, this one’s already very creamy and sweetened just right without actual sugar!!",
    reviewer: " Larisa L. ",
    img: "/images/home/review-product-6.png",
    product: " Vietnamese Coffee 2.0 (Instant Milk Latte) ",
  },
  {
    rating: 5,
    title: "If you’re looking for stronger coffee, THIS IS IT!",
    desc: "I’ve been looking for stronger coffee beans since the one I use no longer works for me. And I have to say, Da Nang blend totally delivered! When they say Vietnamese coffee is strong, man, they’re not lying! 😋",
    reviewer: " Jesse C. ",
    img: "/images/home/review-product-7.png",
    product: " DaNang Coffee (Arabica x Robusta) ",
  },
  {
    rating: 4,
    title: "Strong energy boost",
    desc: "Been looking for a strong coffee to try and a friend recommended Cafely to me. I couldn’t decide what to get LOL so I bought all three! Good thing these come in a bundle and I got to save a few bucks. Aroma and taste wise, they’re fantastic! Amazing aroma, got me perked up and feeling more awake LOL. The taste is 100% awesome! Excellent bold coffee flavors in all three. And what a strong energy boost! Delivered exactly what they promised. I felt more focused and energized the whole day! No coffee crash on this one too or jitters. My personal favorite? Saigon, hands down, is the best in taste and aroma. But when the day calls for stronger coffee, Banme works great!",
    reviewer: " Mose C. ",
    img: "/images/home/review-product-8.png",
    product: " Vietnamese Awakening Coffee Trio (Dark Roast) ",
  },
  {
    rating: 5,
    title: "The best instant coffee I’ve ever had!",
    desc: "I’m not usually into instant coffee, but I knew this one was a must-have when my friend made me a cup. I liked it so much this is already my second order! 🫣",
    reviewer: " Mose C. ",
    img: "/images/home/review-product-9.png",
    product: " Vietnamese Coffee 2.0 (Instant Coconut Latte) ",
  },
  {
    rating: 5,
    title: "Definitely better than regular arabica beans",
    desc: "This one has richer and more intense flavors than the regular arabica beans we buy at the grocery. The caffeine rush was unexpected. It’s definitely stronger than the American brands. Overall, 10/10!",
    reviewer: " Rebecca T. ",
    img: "/images/home/review-product-10.png",
    product: " DaLat Coffee (100% Arabica) ",
  },
];
