import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";

const kaiOFont = localFont({
  src: [
    {
      path: "../public/fonts/Kaio-Bold.woff2",
      weight: "700",
    },
    {
      path: "../public/fonts/Kaio-Black.woff2",
      weight: "900",
    },
  ],
  display: "swap",
  variable: "--font-kaio",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(openSans.className, kaiOFont.variable, "antialiased")}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
