import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import QueryProvider from "@/components/providers/query-provider";
import NextAuthProviders from "@/components/providers/next-auth-provider";

const ppSans = localFont({
  src: [
    {
      path: "../public/fonts/PP-Sans.woff2",
    },
  ],
  display: "swap",
  variable: "--font-pp-sans",
});

const figtree = Figtree({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(figtree.className, ppSans.variable, "antialiased")}
        suppressHydrationWarning
      >
        <NextAuthProviders>
          <QueryProvider>{children}</QueryProvider>
        </NextAuthProviders>
      </body>
    </html>
  );
}
